### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by dominicsmorra**

### CODE REVIEW

**Review by simoneVU — COMMENTED** [review]
Generally, not a bad code but there is still a lot of room for improvement.  One main point to work on is to avoid repetitions (using generic functions) and use more meaningful variables' names. 
I 'd also recommend thinking a bit more about the general logic of the program (i.e. inheritance, abstract classes and polymorphism might return useful in your program). 
Hope this helped a bit! Good luck guys!

**Review by koeves — COMMENTED** [review]
Structurally, the code is fine. Separation of classes and their interactions are simple but well defined. However, the implementation needs improvement: there are occurrences of repeated code, unmeaningful variable names, and some long and confusing functions. Try to refactor those crucial parts of your code so that it can be more easily maintained. The repeated code problem can be solved by writing more general functions. That also makes your code more extensible.

**Review by EGAlberts — APPROVED** [review]
Overall good job, keep it up. Some of your diagrams have mistakes, please look into these and revise them. I then recommend keeping a close eye on the diagrams as you implement further, and taking into account the feedback received on your code and keeping them in mind as you write more code.

**Review by FrankCdeJong — COMMENTED** [review]
Overall I think this code is pretty good. The program works and is very clear on how to set up a league because it walks you through the steps. This could maybe also be applied to the other commands so that anyone who has no idea whats happening could use this. There are a few improvements I suggest to increase readability however these are of course subjective. I suggest you add a .gitignore file to ignore local files which should not be in the repository e.g. .gradle/, .settings/, bin/ etc.

**Review by zack-the-coder — COMMENTED** [review]
While there are some issues with the readability because of some poor naming of variables and long nested functions, the overall quality of the code is GOOD. I would strongly suggest to consider a hashmap for storing the players. Good luck with next one!

**Pull request closed without merging**
